### ISSUE TITLE
[P3B-3]

### ISSUE THREAD

**Issue by WindzCUHK** [ierg4210/shop50#1]
Users are allowed to update its quantity and delete it with a number input

No know it is browser problem.

OS X 10.9.5 (13F1077)
Chrome Version 42.0.2311.135 (64-bit)

Testing page: https://store50.ierg4210.org/product?pid=4
1. add the product
2. change value in text input
3. keep on showing 1, cart value is also 1...

**Comment by williamchong007** [comment]
confirm on Win7 chrome Version 42.0.2311.135 m

**Comment by sktgintokii** [comment]
Fixed
