### ISSUE TITLE
CSRF - Login

### ISSUE THREAD

**Issue by WindzCUHK** [ierg4210/shop50#2]
Detailed steps
1. go to https://store50.ierg4210.org/account, it will redirect to login page
2. go to attacker website http://www.cse.cuhk.edu.hk/~wkfan2/ierg4210/store50-CSRF.html
3. go to https://store50.ierg4210.org/account, login with test AC KO...

What did you see?
login in success and get the session id in cookies

What did you expect to see?
redirect to login page

Fix:
Introduce nonce in the shopping cart, and check for every incoming request that is the nonce valid

**Comment by sktgintokii** [comment]
OK now
