### ISSUE TITLE
Possible Man in the Middle Attack

### ISSUE THREAD

**Issue by s1155031145** [ierg4210/shop50#4]
Detailed steps to reproduce? access the /account/login page and use a wireshark to capture the data
What did you see? password in plaintext
What did you expect to see? password encrypted
What is the possible fix? enforce https

Proof: http://postimg.org/image/m5er8cub7/

**Comment by sktgintokii** [comment]
Thx for report.
Now I redirect all traffic to https not limit to admin panel.
